version: '3'
services:
  website:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  test:
    container_name: test
    image: nginx:latest
    ports:
      - '1080:80'
      - '1443:443'
    restart: always
  toast:
    container_name: toast
    image: nginx:latest
    ports:
      - '1080:80'
      - '1443:443'
    restart: always
